### ISSUE TITLE
Can't install Discord RP

### ISSUE THREAD

**Issue by sleepymanakete** [AnonGuy/discordrp-pcsx2#3]
When I run `pip install discordrp-pcsx2`, I get:
`ERROR: Could not find a version that satisfies the requirement discordrp-pcsx2 (from versions: none)
ERROR: No matching distribution found for discordrp-pcsx2`

I tried updating python but that didn't fix it.

**Comment by AnonGuy** [comment]
Hi @sleepymanakete,

Are you using Python 2 or 3?

**Comment by sleepymanakete** [comment]
Hello. I am using Python 3.

**Comment by AnonGuy** [comment]
What version of Python 3?

**Comment by AnonGuy** [comment]
discordrp-pcsx2 currently supports Python 3.6+

**Comment by sleepymanakete** [comment]
Python 3.6.5 is what I'm using.

**Comment by sleepymanakete** [comment]
Ok so I updated to python 3.7 and made sure its added to the path. It works now, thanks for the help!
