### ISSUE TITLE
Path Setting dosen't work

### ISSUE THREAD

**Issue by Scheux** [AnonGuy/discordrp-pcsx2#4]
Hey, It can be that i'm a little bit dumb but
Everytime when i try to set a Path for discordrp-pcsx2 it says to me "Access Denied" 
but i do the command like it is written in the Readme

Am i doing something wrong?

Sorry if i'm annoying with this

**Comment by KnightIV** [comment]
Hey, I just had this issue as well, have you tried opening the console as Admin?

Alternatively, what I believe fixed it for me was opening the console from the Windows Explorer in my root PCSX2 folder.
