### ISSUE TITLE
make a guide

### ISSUE THREAD

**Issue by ANDREMELENDEZ** [AnonGuy/discordrp-pcsx2#5]
could you make a more thorough guide on how to make this rich presence thing work

**Comment by RejectedGalaxy** [comment]
Yeah I agree, I don't really know how to use python. I tried but I couldn't get it to work still.

**Comment by Jresh** [comment]
cant figure out how to install this lmao, great idea though

**Comment by Newtochr** [comment]
Agree with the others.

**Comment by Stellasin** [comment]
Yeah same, I have python but no idea how to use it. A proper installation guide would be nice
